version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          TZ: "/usr/share/zoneinfo/Europe/Amsterdam"
    steps:
      - checkout
      - run: gem update bundler

      # Bundle install dependencies
      - run: bundle install

      - run: rake spec
